name: Deploy Cloudflare Workers

on:
  push:
    branches:
      - staging
  create:
    tags: ["v*"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy-preview
        if: github.ref == 'refs/heads/develop'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: "4.16.1"
          preCommands: npx vite build --mode preview
          command: |
            d1 migrations apply DB --remote --env preview
            deploy

      - name: Deploy-prod
        if: startsWith(github.ref, 'refs/tags/v')
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: "4.16.1"
          preCommands: npx vite build --mode production
          command: |
            d1 migrations apply DB --remote --env production
            deploy
